[package]
name = "drand_quicknet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { path = "../.." }
starknet = "2.14.0"

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
