[package]
name = "noir_ultra_starknet_honk_example"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { path = "../../../" }
starknet = "2.12.2"

[cairo]
sierra-replace-ids = false
inlining-strategy = 2

[dev-dependencies]
snforge_std = "0.51.1"
assert_macros = "2.12.2"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
