[workspace]
members = [
    "src/",
    "src/corelib_imports",
]

[workspace.dependencies]
cairo_test = "2.14.0"
starknet = "2.14.0"

[workspace.scripts]
test = "snforge test -p garaga --include-ignored"

[cairo]
sierra-replace-ids = false
