[package]
name = "noir_ultra_keccak_zk_honk_example"
version = "0.1.0"
edition = "2023_10"

[dependencies]
garaga = { path = "../../" }
starknet = "2.11.2"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
cairo_test = "2.11.2"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
