[package]
name = "kakarot_endpoints"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { path = ".." }
starknet = "2.7.0"

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]