[package]
name = "garaga"
version = "0.1.0"
licence = "MIT"
keywords = ["zk", "snarks", "curve", "pairing", "groth16", "plonk", "bls", "elliptic", "signature"]
description = "State-of-the-art Elliptic Curve operations and SNARKS verification for Cairo & Starknet"
readme = "../../README.md"
repository = "https://github.com/keep-starknet-strange/garaga"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[workspace]
members = ["garaga_contracts"]
[dependencies]

[dev-dependencies]
cairo_test = "2.6.4+nightly-2024-06-19"
[cairo]
sierra-replace-ids = false